version: "3"

services:
  base: &base
    image: ${DOCKER_IMAGE:-solnic/hanami-docker_demo}:${DOCKER_TAG:-latest}
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  development:
    <<: *base
    build:
      context: .
      target: development
    entrypoint: script/development
    env_file: [.env, .env.development]

  test:
    <<: *base
    build:
      context: .
      target: test
    entrypoint: script/test
    env_file: [.env, .env.test]

volumes:
  bundle:
