#!/usr/bin/env bash

set -e

bundle check || bundle

if [ $# -eq 0 ]; then
  [[ -f log/development.log ]] || touch log/development.log
  tail -f log/development.log
else
  echo "Running $@"
  exec $@
fi
